apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployement
  labels:
    app: wescribe-frontend
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: wescribe-frontend
  template: 
    metadata:
      labels:
        app: wescribe-frontend
    spec:
      containers:
        - name: frontend-container
          image: dhanush29/wescribe-frontend:latest
          imagePullPolicy: Always
          ports:
          - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-svc
spec:
  type: NodePort
  selector:
    app: wescribe-frontend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30000