- name: Deployment on Kubernetes cluster
  hosts: host_machine
  tasks:

    # - name: Check Minikube status
    #   command: minikube status
    #   register: minikube_status
    #   changed_when: false
    #   failed_when: false

    # - name: Start Minikube
    #   become: false
    #   command: minikube start
    #   when: "'Running' not in minikube_status.stdout"

    - name: Applying Kubernetes Command in Repository
      shell: |
        cd ./kubernetes/
        kubectl delete -f .
        kubectl apply -f .
      changed_when: false
      failed_when: false