apiVersion: apps/v1
kind: Deployment
metadata:
  name: wescribe-frontend-deployement
  labels:
    app: wescribe-frontend-deployement
spec:
  replicas: 2
  selector: 
    matchLabels:
      app: wescribe-frontend-deployement
  template: 
    metadata:
      labels:
        app: wescribe-frontend-deployement
    spec:
      containers:
        - name: wescribe-frontend
          image: dhanush29/wescribe-frontend:latest
          imagePullPolicy: Always
          ports:
          - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: wescribe-frontend-svc
spec:
  selector:
    app: wescribe-frontend-deployement
  type: LoadBalancer
  loadBalancerIP: "0.0.0.0"
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30001